### PR TITLE
fix(welcomeNotification): add button to ignore requirement checks

### LINKED ISSUE #34: atom-ide-ui not recognized in Nuclide bundle
atom-ide-ui is bundled with Nuclide IDE, but this package keeps displaying a warning prompting to install it

This package should recognize Nuclide as satisfying atom-ide-ui dependency

### PR DESCRIPTION
**Pull request by liuderchi**
try to fix #34

### CODE REVIEW

File: src/welcome_notification.js [hunk 1]
```diff
@@ -17,37 +18,37 @@ const generateWelcomeMsg = () => {
   }\nHappy Using Atom IDE : )`
 }
 
+// TODO make it pure
 const generateWarnMsg = () => {
   return `## Welcome to ${pkgName}\n\nPlease install and activate these requirements:\n${
     requirements
-      .map((name, i) => `${i}. [\`${name}\`](https://atom.io/packages/${name})\n`)
+      .map((name, i) => `${i+1}. [\`${name}\`](https://atom.io/packages/${name})\n`)
```
Comment (liuderchi) [inline src/welcome_notification.js]: starts from 1 rather than 0

File: src/welcome_notification.js [hunk 2]
```diff
@@ -57,17 +58,27 @@ const checkRequirementsThenWelcome = () => {
       atom.notifications.addSuccess(
         generateWelcomeMsg(),
         {
-          buttons: helpButton,
+          buttons: [helpButton],
```
Comment (liuderchi) [inline src/welcome_notification.js]: more readable API
